### PR TITLE
Add s3 deploy configs

### PR DESCRIPTION
**Pull request by josiahsprague**
Add configs for deploying to S3. @pushred I'm not sure that these configs are actually share-able, with the `bucket_name`, `region`, etc being defined in the config.

### CODE REVIEW

**Comment by pushred** [comment]
Yeah that's what https://github.com/SparkartGroupInc/qa-deployer/pull/11 is supposed to address.

**Comment by pushred** [comment]
Can you give that a whirl? One repo I just encountered that'll break my thesis: https://github.com/SparkartGroupInc/epicscale-app. But surely it'll have a domain of some form.

**Comment by josiahsprague** [comment]
@pushred Can you give me access to epicscale-app so I can see what you're talking about?

**Comment by pushred** [comment]
Added

**Comment by josiahsprague** [comment]
`config/deploy-s3-production.js` will pull the project name dynamically from the project's package.json. I am tempted to change all of the config files from .json to .js for consistency, but that would be a breaking change for all of the open PRs that are relying on shared configs from broadway. Granted it'd be pretty easy since I've got a list of all of those PRs that I can go through and update. But since the s3 production deploys are the only ones that need the dynamic project name at the moment, maybe we can just change the extension of this one file and update the 3 open PRs that reference it.

**Comment by josiahsprague** [comment]
Tried this by deploying http://www.littleoilrecords.com/, working smoothly, except for Zapier notifications of a sucessful deploy, which seem to be getting filtered out by Zapier. Not sure if the Zap settings just need updated, or if we need to create a different Zap.

**Comment by joanniclaborde** [comment]
If you change all extensions for consistency, as you were saying, you can then remove the extensions completely from those PRs. qa-deployer uses `require` to [load the config file](https://github.com/SparkartGroupInc/qa-deployer/blob/master/src/utils/cli.js#L11), so the extension can be safely ignored.

**Comment by josiahsprague** [comment]
Updated all of those PRs and a small handful of sites where the PR was already merged. I overwhelmed Circle and/or Modulus, so the builds are still pending, but, we should be good to go to use either .js or .json extensions here.

**Comment by josiahsprague** [comment]
Before this is ready to merge:

- [ ] Merge https://github.com/SparkartGroupInc/qa-deployer/pull/11 and update package.json to point back to npm repo

**Pull request merged**
